version: '3.8'

services:
  task-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-scheduler
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
        # Binance API 配置 - 从 .env 文件读取
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
      - HTTP_PROXY=http://host.docker.internal:7890
      - HTTPS_PROXY=http://host.docker.internal:7890
    extra_hosts:  # 确保容器能解析宿主IP
      - "host.docker.internal:host-gateway"
    volumes:
      # 挂载配置文件目录，方便修改配置
      - ./configs:/app/configs:ro
      # 挂载数据目录，持久化 AHR999 历史数据
      - ./data:/app/plugins/auto-buy/ahr999_history
    networks:
      - task-scheduler-network
    # 如果需要暴露端口（比如有 Web 界面）
    # ports:
    #   - "8080:8080"
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "task_scheduler"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  task-scheduler-network:
    driver: bridge 