version: '3.8'

services:
  task-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-scheduler
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      # 挂载配置文件目录，方便修改配置
      - ./configs:/app/configs:ro
      # 挂载数据目录，持久化 AHR999 历史数据
      - ./data:/app/plugins/auto-buy/ahr999_history
    networks:
      - task-scheduler-network
    # 如果需要暴露端口（比如有 Web 界面）
    # ports:
    #   - "8080:8080"
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "task_scheduler"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  task-scheduler-network:
    driver: bridge 