schedule: "0 0 8 * * *"  # 每日上午8点执行
params:
  enabled: true
  debug: false 
  base_amount: 100
  ahr999_timer_table: |
    {
      "<0.45": 5,
      "0.45-0.6": 3,
      "0.6-0.8": 2,
      "0.8-0.9": 1.5,
      "0.9-1.1": 1,
      "1.1-1.2": 0.75,
      "1.2-1.4": 0.5,
      "1.4-2": 0.25,
      ">2": 0
    }